# copy this to docker-compose.yml and update with your specific values.
# ** Careful not to commit passwords if you're planning to publically host this in a git repo somewhere! **
version: "2"

# create and launch these containers (after tweaking the configuration files) with 'docker-compose up'
services:
    mautic:
        image: kiwilightweight/mautic
        links:
           - mauticdb:mysql
        # create a suitable database before running 'docker-compose up'
        environment:
            MAUTIC_DB_HOST: mysql
            MAUTIC_DB_USER: mautic
            MAUTIC_DB_PASSWORD: mauticdbpass
        ports:
            - 127.0.0.1:9000:9000
        volumes:
            - /docker/src:/var/www/html
            - /docker/msmtprc:/etc/msmtprc
            - /docker/sslcerts:/etc/letsencrypt
        restart:
            unless-stopped
    mauticdb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: mysqlrootpassword
            MYSQL_DATABASE: mautic
            MYSQL_USER: mautic
            MYSQL_PASSWORD: mauticdbpass
# #
# # this is optional - alternatively, you can use the "conf.d/default.conf" as the basis
# # for an nginx site conf file on your Docker host. In the latter case, comment this
# # whole section out.
#    nginx:
#        image: nginx
#        links:
#            - mautic:mautic
#        ports:
#            #  If running this locally - requires reverse proxy for external visibility
#            - 127.0.0.1:8083:80
#            # If running the nginx container exposed directly to the 'net
# #           - 127.0.0.1:80:80
#        volumes:
#            - [your local mautic directory, nginx default.conf file]:/etc/nginx/sites-available/default
#            - [your local mautic directory, prob same as above]:/var/www/html
#        restart:
#            unless-stopped
