nginx:
  build: nginx-image
  links:
    - app
  environment:
    - MY_DOMAIN_NAME=mautic2.welo.love
  mem_limit: 2g
  cpu_shares: 256
  # restart: always
  ports: 
    - "80:80"
    - "443:443"
   volumes:
    - lets:/etc/letsencrypt
    - lets:/var/lib/letsencrypt
app:
  build: app-image
  links:
    - mysql
  ports:
    - "80"
mysql:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: mysqlrootpassword
    MYSQL_DATABASE: mautic
    MYSQL_USER: mautic
    MYSQL_PASSWORD: mauticdbpass
