version: "2"
services:
  nginx:
    build: app-image
    links:
      - mysql
    environment:
      - MY_DOMAIN_NAME=mautic3.welo.love
    mem_limit: 2g
    cpu_shares: 256
    # restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - sslcerts_2:/etc/letsencrypt
      - sslcerts_2:/var/lib/letsencrypt
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mauticdbpass
volumes:
 sslcerts_2:  #declare a volume named pgvolume