nginx:
  build: app-image
  links:
    - mysql
  environment:
    - MY_DOMAIN_NAME=mautic.spreadwe.love
  mem_limit: 2g
  cpu_shares: 256
  # restart: always
  ports: 
    - "80:80"
    - "443:443"
  volumes:
    - /docker/sslcert:/etc/letsencrypt
    - /docker/sslcert:/var/lib/letsencrypt
  # letsencrypt:
  #   image: quay.io/letsencrypt/letsencrypt:latest
  #   command:  bash -c "sleep 6 && certbot certonly --standalone -d mautic.spreadwe.love --text --agree-tos --email eugenio00@gmail.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
  #   entrypoint: ""
  #   volumes:
  #     - /docker/sslcert:/etc/letsencrypt
  #     - /docker/sslcert:/var/lib/letsencrypt
  #   ports:
  #     - "80"
  #     - "443"
  #   environment:
  #     - TERM=xterm
mysql:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: mysqlrootpassword
    MYSQL_DATABASE: mautic
    MYSQL_USER: mautic
    MYSQL_PASSWORD: mauticdbpass
