version: "2"
services:
  nginx:
    build: app-image
    depends_on:
      - letsencrypt
      - mysql
    environment:
      - MY_DOMAIN_NAME=mautics.welo.love
    # restart: always
    ports:
      - "80"
      - "443"
    volumes:
      - sslcerts_2:/etc/letsencrypt
      - sslcerts_2:/var/lib/letsencrypt

  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    command:  bash -c "sleep 6 && certbot certonly --standalone -d mautics.welo.love --text --agree-tos --email eugenio00@gmail.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
    entrypoint: ""
    volumes:
      - sslcerts_2:/etc/letsencrypt
      - sslcerts_2:/var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mauticdbpass
volumes:
 sslcerts_2:  "./sslcerts"