nginx:
  build: app-image
  links:
    - mysql
  environment:
    - MY_DOMAIN_NAME=mautic.spreadwe.love
  mem_limit: 2g
  cpu_shares: 256
  # restart: always
  ports: 
    - "80:80"
    - "443:443"
  volumes:
    - /docker/sslcert:/etc/letsencrypt
    - /docker/sslcert:/var/lib/letsencrypt
mysql:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: mysqlrootpassword
    MYSQL_DATABASE: mautic
    MYSQL_USER: mautic
    MYSQL_PASSWORD: mauticdbpass
