nginx:
  build: nginx-image
  links:
    - letsencrypt
    - app
  environment:
    - MY_DOMAIN_NAME=mautic2.welo.love
  mem_limit: 2g
  cpu_shares: 256
  # restart: always
  ports: 
    - "80:80"
    - "443:443"
  volumes_from:
    - letsencrypt
letsencrypt:
  image: quay.io/letsencrypt/letsencrypt:latest
  command:  bash -c "sleep 6 && certbot certonly --standalone -d mautic2.welo.love --text --agree-tos --email eugenio00@gmail.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
  entrypoint: ""
  volumes:
    - letsencryptLibetc:/etc/letsencrypt
    - letsencryptLib:/var/lib/letsencrypt
  ports:
    - "80"
    - "443"
  environment:
    - TERM=xterm
app:
  build: app-image
  links:
    - mysql
  ports:
    - "80"
mysql:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: mysqlrootpassword
    MYSQL_DATABASE: mautic
    MYSQL_USER: mautic
    MYSQL_PASSWORD: mauticdbpass
